# Play level Variable is called in Task
- name: Play level variable
  hosts: localhost
  vars:
    URL: play-level.example.com
  tasks:
    - name: Print from variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

# Variable is called from a file
- name: variable from file
  hosts: localhost
  vars_files:
    - ex-var.yml
  tasks:
    - name: Print from var file
      ansible.builtin.debug:
        msg: URL = {{ URL }}

# Task level variables cannot be accessed from another task
- name: Task level variable
  hosts: localhost
  tasks:
    - name: print from task level var
      vars:
        URL: task-level.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

# Variable is called from Inventory file
# Here in below example "ansible_hostname" is a predefined variable by Ansible called as Ansible facts
- name: Inventory level variable
  hosts: all
  tasks:
    - name: print from Inventory
      ansible.builtin.debug:
        msg: URL = {{ URL }} hostname ={{ ansible_hostname }}

# Registering the output and printing the output
- name: Register a variable
  hosts: all
  tasks:
    - name: shell uptime variable
      ansible.builtin.shell: uptime
      register: OUT # register is a runtime variable it stores the output of the task

    - name: Printing output
      ansible.builtin.debug:
        msg: "{{ OUT }}"

# Registering the exit status in set_fact task
    - name: Declare a variable
      ansible.builtin.set_fact: # set_fact stores the output in a standard variable
        status: "{{ OUT.rc }}"

# calling the status from set_fact task
    - name: printing the output
      ansible.builtin.debug:
        msg: "{{ status }}"

#  example, we can call directly particular value from var ex: [OUT.end]
#    - name: printing the output
#      ansible.builtin.debug:
#        msg: "{{ OUT.end }}"
