# Play level Variable is called in Task
- name: Play level variable
  hosts: localhost
  vars:
    URL: play-level.example.com
  tasks:
    - name: Print from variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

# Variable is called from a file
- name: variable from file
  hosts: localhost
  vars_files:
    - ex-var.yml
  tasks:
    - name: Print from var file
      ansible.builtin.debug:
        msg: URL = {{ URL }}

# Task level variables cannot be accessed from another task
- name: Task level variable
  hosts: localhost
  tasks:
    - name: print from task level var
      vars:
        URL: task-level.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

# Variable is called from Inventory file
- name: Inventory level variable
  hosts: all
  tasks:
    - name: print from Inventory
      ansible.builtin.debug:
        msg: URL = {{ URL }} hostname ={{ ansible_hostname }}

#
#- name: