- name: Demo Play var
  hosts: localhost
  vars:
    URL: www.google.com
  tasks:
    - name: Print from variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Demo Play var from file
  hosts: localhost
  var.files:
    - ex-var.yml
  tasks:
    - name: Print from var file
      ansible.builtin.debug:
        msg: URL = {{ URL }}